### ISSUE TITLE
Error in getSignal(obj, timeIncSec)

### ISSUE THREAD

**Issue by abaebae** [TWOEARS/TwoEars#1]
I just ran the examples provided in the section "First steps: Binaural renderer" (Matlab 2014b, Mac OS X), but couldn't get the signal with

``` matlab
signal = sim.getSignal();
```

as specified in the example. The `nargin` check in line 330 in `SimulatorConvexRoom.m` fails if no value vor `timeIncSec` is handed over, but should set it to `inf`

``` matlab
if nargin < 1 % should be nargin < 2
        timeIncSec = inf;
end 
```

**Comment by fietew** [comment]
Fixed by 753dada8ee47da8e76bcc3e9a3f7f82a6c051fa4 
Thanks for pointing it out
