### ISSUE TITLE
Matlab 2015b: wavread support dropped

### ISSUE THREAD

**Issue by dennisguse** [TWOEARS/TwoEars#3]
http://de.mathworks.com/help/matlab/ref/wavread.html

Although usage of audioread is suggested as a drop-in replacement, it seems to have trouble, if too many channels are used.

**Comment by fietew** [comment]
Fixed this with own implementation of wavwrite, named savewav. See TWOEARS/binaural-simulator@db2d6d4 

Thanks for pointing this out!

**Comment by dennisguse** [comment]
Wavread == wavwrite?
